name: cinemo
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.10
  - pytorch >= 2.0
  - torchvision
  - pytorch-cuda >= 11.7
  - pip:
    - timm
    - diffusers[torch]==0.24.0
    - accelerate
    - python-hostlist
    - tensorboard
    - einops
    - transformers
    - av
    - scikit-image
    - decord
    - pandas